// Unit acknowledgment voice manifest — generated by scripts/gen-voices.sh
// Shape: { [unitKey]: { select: [paths], move: [paths], attack: [paths] } }
// Paths are relative to public/sfx/ (e.g. 'voice/trooper_select1.mp3').
// NOTE: dozer is shared between coalition and dominion — one voice set.
export const VOICES = {
  // ── COALITION ─────────────────────────────────────────────────────────────
  trooper: {
    select: ['voice/trooper_select1.mp3', 'voice/trooper_select2.mp3'],
    move:   ['voice/trooper_move1.mp3',   'voice/trooper_move2.mp3'],
    attack: ['voice/trooper_attack1.mp3', 'voice/trooper_attack2.mp3'],
  },
  javelin: {
    select: ['voice/javelin_select1.mp3', 'voice/javelin_select2.mp3'],
    move:   ['voice/javelin_move1.mp3',   'voice/javelin_move2.mp3'],
    attack: ['voice/javelin_attack1.mp3', 'voice/javelin_attack2.mp3'],
  },
  marksman: {
    select: ['voice/marksman_select1.mp3', 'voice/marksman_select2.mp3'],
    move:   ['voice/marksman_move1.mp3',   'voice/marksman_move2.mp3'],
    attack: ['voice/marksman_attack1.mp3', 'voice/marksman_attack2.mp3'],
  },
  ghost: {
    select: ['voice/ghost_select1.mp3', 'voice/ghost_select2.mp3'],
    move:   ['voice/ghost_move1.mp3',   'voice/ghost_move2.mp3'],
    attack: ['voice/ghost_attack1.mp3', 'voice/ghost_attack2.mp3'],
  },
  dozer: {
    select: ['voice/dozer_select1.mp3', 'voice/dozer_select2.mp3'],
    move:   ['voice/dozer_move1.mp3',   'voice/dozer_move2.mp3'],
    attack: ['voice/dozer_attack1.mp3', 'voice/dozer_attack2.mp3'],
  },
  pelican: {
    select: ['voice/pelican_select1.mp3', 'voice/pelican_select2.mp3'],
    move:   ['voice/pelican_move1.mp3',   'voice/pelican_move2.mp3'],
    attack: ['voice/pelican_attack1.mp3', 'voice/pelican_attack2.mp3'],
  },
  outrider: {
    select: ['voice/outrider_select1.mp3', 'voice/outrider_select2.mp3'],
    move:   ['voice/outrider_move1.mp3',   'voice/outrider_move2.mp3'],
    attack: ['voice/outrider_attack1.mp3', 'voice/outrider_attack2.mp3'],
  },
  paladin: {
    select: ['voice/paladin_select1.mp3', 'voice/paladin_select2.mp3'],
    move:   ['voice/paladin_move1.mp3',   'voice/paladin_move2.mp3'],
    attack: ['voice/paladin_attack1.mp3', 'voice/paladin_attack2.mp3'],
  },
  tempest: {
    select: ['voice/tempest_select1.mp3', 'voice/tempest_select2.mp3'],
    move:   ['voice/tempest_move1.mp3',   'voice/tempest_move2.mp3'],
    attack: ['voice/tempest_attack1.mp3', 'voice/tempest_attack2.mp3'],
  },
  specter: {
    select: ['voice/specter_select1.mp3', 'voice/specter_select2.mp3'],
    move:   ['voice/specter_move1.mp3',   'voice/specter_move2.mp3'],
    attack: ['voice/specter_attack1.mp3', 'voice/specter_attack2.mp3'],
  },
  falcon: {
    select: ['voice/falcon_select1.mp3', 'voice/falcon_select2.mp3'],
    move:   ['voice/falcon_move1.mp3',   'voice/falcon_move2.mp3'],
    attack: ['voice/falcon_attack1.mp3', 'voice/falcon_attack2.mp3'],
  },
  meteor: {
    select: ['voice/meteor_select1.mp3', 'voice/meteor_select2.mp3'],
    move:   ['voice/meteor_move1.mp3',   'voice/meteor_move2.mp3'],
    attack: ['voice/meteor_attack1.mp3', 'voice/meteor_attack2.mp3'],
  },

  // ── DOMINION ──────────────────────────────────────────────────────────────
  conscript: {
    select: ['voice/conscript_select1.mp3', 'voice/conscript_select2.mp3'],
    move:   ['voice/conscript_move1.mp3',   'voice/conscript_move2.mp3'],
    attack: ['voice/conscript_attack1.mp3', 'voice/conscript_attack2.mp3'],
  },
  hunter: {
    select: ['voice/hunter_select1.mp3', 'voice/hunter_select2.mp3'],
    move:   ['voice/hunter_move1.mp3',   'voice/hunter_move2.mp3'],
    attack: ['voice/hunter_attack1.mp3', 'voice/hunter_attack2.mp3'],
  },
  hacker: {
    select: ['voice/hacker_select1.mp3', 'voice/hacker_select2.mp3'],
    move:   ['voice/hacker_move1.mp3',   'voice/hacker_move2.mp3'],
    attack: ['voice/hacker_attack1.mp3', 'voice/hacker_attack2.mp3'],
  },
  mantis: {
    select: ['voice/mantis_select1.mp3', 'voice/mantis_select2.mp3'],
    move:   ['voice/mantis_move1.mp3',   'voice/mantis_move2.mp3'],
    attack: ['voice/mantis_attack1.mp3', 'voice/mantis_attack2.mp3'],
  },
  supplyTruck: {
    select: ['voice/supplyTruck_select1.mp3', 'voice/supplyTruck_select2.mp3'],
    move:   ['voice/supplyTruck_move1.mp3',   'voice/supplyTruck_move2.mp3'],
    attack: ['voice/supplyTruck_attack1.mp3', 'voice/supplyTruck_attack2.mp3'],
  },
  warmaster: {
    select: ['voice/warmaster_select1.mp3', 'voice/warmaster_select2.mp3'],
    move:   ['voice/warmaster_move1.mp3',   'voice/warmaster_move2.mp3'],
    attack: ['voice/warmaster_attack1.mp3', 'voice/warmaster_attack2.mp3'],
  },
  shredder: {
    select: ['voice/shredder_select1.mp3', 'voice/shredder_select2.mp3'],
    move:   ['voice/shredder_move1.mp3',   'voice/shredder_move2.mp3'],
    attack: ['voice/shredder_attack1.mp3', 'voice/shredder_attack2.mp3'],
  },
  dragon: {
    select: ['voice/dragon_select1.mp3', 'voice/dragon_select2.mp3'],
    move:   ['voice/dragon_move1.mp3',   'voice/dragon_move2.mp3'],
    attack: ['voice/dragon_attack1.mp3', 'voice/dragon_attack2.mp3'],
  },
  hellstorm: {
    select: ['voice/hellstorm_select1.mp3', 'voice/hellstorm_select2.mp3'],
    move:   ['voice/hellstorm_move1.mp3',   'voice/hellstorm_move2.mp3'],
    attack: ['voice/hellstorm_attack1.mp3', 'voice/hellstorm_attack2.mp3'],
  },
  emperor: {
    select: ['voice/emperor_select1.mp3', 'voice/emperor_select2.mp3'],
    move:   ['voice/emperor_move1.mp3',   'voice/emperor_move2.mp3'],
    attack: ['voice/emperor_attack1.mp3', 'voice/emperor_attack2.mp3'],
  },
  vulture: {
    select: ['voice/vulture_select1.mp3', 'voice/vulture_select2.mp3'],
    move:   ['voice/vulture_move1.mp3',   'voice/vulture_move2.mp3'],
    attack: ['voice/vulture_attack1.mp3', 'voice/vulture_attack2.mp3'],
  },

  // ── SYNDICATE ─────────────────────────────────────────────────────────────
  worker: {
    select: ['voice/worker_select1.mp3', 'voice/worker_select2.mp3'],
    move:   ['voice/worker_move1.mp3',   'voice/worker_move2.mp3'],
    attack: ['voice/worker_attack1.mp3', 'voice/worker_attack2.mp3'],
  },
  militant: {
    select: ['voice/militant_select1.mp3', 'voice/militant_select2.mp3'],
    move:   ['voice/militant_move1.mp3',   'voice/militant_move2.mp3'],
    attack: ['voice/militant_attack1.mp3', 'voice/militant_attack2.mp3'],
  },
  stinger: {
    select: ['voice/stinger_select1.mp3', 'voice/stinger_select2.mp3'],
    move:   ['voice/stinger_move1.mp3',   'voice/stinger_move2.mp3'],
    attack: ['voice/stinger_attack1.mp3', 'voice/stinger_attack2.mp3'],
  },
  fanatic: {
    select: ['voice/fanatic_select1.mp3', 'voice/fanatic_select2.mp3'],
    move:   ['voice/fanatic_move1.mp3',   'voice/fanatic_move2.mp3'],
    attack: ['voice/fanatic_attack1.mp3', 'voice/fanatic_attack2.mp3'],
  },
  cobra: {
    select: ['voice/cobra_select1.mp3', 'voice/cobra_select2.mp3'],
    move:   ['voice/cobra_move1.mp3',   'voice/cobra_move2.mp3'],
    attack: ['voice/cobra_attack1.mp3', 'voice/cobra_attack2.mp3'],
  },
  technical: {
    select: ['voice/technical_select1.mp3', 'voice/technical_select2.mp3'],
    move:   ['voice/technical_move1.mp3',   'voice/technical_move2.mp3'],
    attack: ['voice/technical_attack1.mp3', 'voice/technical_attack2.mp3'],
  },
  scorpion: {
    select: ['voice/scorpion_select1.mp3', 'voice/scorpion_select2.mp3'],
    move:   ['voice/scorpion_move1.mp3',   'voice/scorpion_move2.mp3'],
    attack: ['voice/scorpion_attack1.mp3', 'voice/scorpion_attack2.mp3'],
  },
  quad: {
    select: ['voice/quad_select1.mp3', 'voice/quad_select2.mp3'],
    move:   ['voice/quad_move1.mp3',   'voice/quad_move2.mp3'],
    attack: ['voice/quad_attack1.mp3', 'voice/quad_attack2.mp3'],
  },
  toxinTractor: {
    select: ['voice/toxinTractor_select1.mp3', 'voice/toxinTractor_select2.mp3'],
    move:   ['voice/toxinTractor_move1.mp3',   'voice/toxinTractor_move2.mp3'],
    attack: ['voice/toxinTractor_attack1.mp3', 'voice/toxinTractor_attack2.mp3'],
  },
  buggy: {
    select: ['voice/buggy_select1.mp3', 'voice/buggy_select2.mp3'],
    move:   ['voice/buggy_move1.mp3',   'voice/buggy_move2.mp3'],
    attack: ['voice/buggy_attack1.mp3', 'voice/buggy_attack2.mp3'],
  },
  scud: {
    select: ['voice/scud_select1.mp3', 'voice/scud_select2.mp3'],
    move:   ['voice/scud_move1.mp3',   'voice/scud_move2.mp3'],
    attack: ['voice/scud_attack1.mp3', 'voice/scud_attack2.mp3'],
  },
};
