#!/usr/bin/env python3
"""Downscale baked icon art (assets-raw/icons/*.png, 1024px) to
public/icons/*.webp and regenerate src/ui/icon-manifest.js."""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets-raw', 'icons')
DST = os.path.join(ROOT, 'public', 'icons')
SIZE = 192  # largest HUD slot is 60px; 192 covers 3x density
os.makedirs(DST, exist_ok=True)

keys = []
for f in sorted(os.listdir(SRC)):
    if not f.endswith('.png'):
        continue
    key = f[:-4]
    keys.append(key)
    out = os.path.join(DST, key + '.webp')
    src = os.path.join(SRC, f)
    if os.path.exists(out) and os.path.getmtime(out) >= os.path.getmtime(src):
        continue
    Image.open(src).convert('RGB').resize((SIZE, SIZE), Image.LANCZOS).save(out, 'WEBP', quality=82)
    print('→', key + '.webp')

manifest = os.path.join(ROOT, 'src', 'ui', 'icon-manifest.js')
with open(manifest, 'w') as f:
    f.write('// AUTO-GENERATED by scripts/convert-icons.py — do not edit.\n')
    f.write('// Keys with baked painted art in /public/icons/<key>.webp.\n')
    f.write('export const ICON_ART = new Set([\n')
    for k in keys:
        f.write(f"  '{k}',\n")
    f.write(']);\n')
print(f'{len(keys)} icons in manifest')
